# Generated by Django 3.0.2 on 2020-02-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLanding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
